"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_TENANT = exports.REQUEST_TIMEOUT = exports.CONNECTION_TIMEOUT = exports.KEEP_ALIVE_TIMEOUT = exports.TENANT = exports.CONNECTION_ID = void 0;
const connect_1 = require("@connectrpc/connect");
exports.CONNECTION_ID = (0, connect_1.createContextKey)("connectionId");
exports.TENANT = (0, connect_1.createContextKey)("connectionId");
exports.KEEP_ALIVE_TIMEOUT = 20000;
exports.CONNECTION_TIMEOUT = 5000;
exports.REQUEST_TIMEOUT = 5000;
exports.DEFAULT_TENANT = "default";
